### ISSUE TITLE
Add `library/cpp/testing/benchmark` library

### ISSUE THREAD

**Issue by tsayukov** [ydb-platform/ydb-cpp-sdk#296]
Требуется для теста `util/system/unaligned_mem_ut.cpp` из #164

**Comment by Gazizonoki** [comment]
benchmark тащит за собой слишком много либ, вроде linear_regression. Нам по сути нужна только одна функция: NBench::Clobber(). Предлагаю следующее: в src/library скопировать реализацию NBench::Clobber и подменить инклюд в unit тесте
