### ISSUE TITLE
libc_compat

### ISSUE THREAD

**Issue by Gazizonoki** [ydb-platform/ydb-cpp-sdk#93]

**Comment by Gazizonoki** [comment]
Это сборка исходников из различных источников, унифицирует различные libc. Вероятно, надо просто убрать и переписать код так, чтобы не надеяться на либу

**Comment by EshUno** [comment]
Взяла задачу.

**Comment by Gazizonoki** [comment]
@EshUno Это вообще не библиотека, просто куски кода, вырванные из libc в FreeBSD, что ты будешь делать с этой либой? Я сам даже не знаю пока, что с ней делать, ты уверена, что хочешь взять задачу?

**Comment by EshUno** [comment]
@Gazizonoki хотя бы всякие операции со строками/участками памяти (bzero, strlcopy и так далее) заменить на вызовы из STL. Остальные вещи вроде readpassphrase() (getpassphrase.c) - надо сначала понять, что они делают.

**Comment by EshUno** [comment]
Все-таки не поняла, что делать. Лучше откажусь.

**Comment by tsayukov** [comment]
Возьму задачу себе. Есть примерный план, что делать
